### ISSUE TITLE
helpmessage.txt path not found Exception when pressing help button.

### ISSUE THREAD

**Issue by SaturnnrutaS** [osl2/PhyPiDAQ#25]

**Comment by SaturnnrutaS** [comment]
This happens to me even when I start the application from the IDE.

**Comment by stefan-geretschlaeger** [comment]
Symptom: PathNotFoundException is thrown when pressing help button (at Windows: both on IDE and fat-jar, at Linux: only at fat-jar) 
Cause: gui.helpandoption.HelpWindow.loadData() and its call at constructor:  circumstancial resource-loading (first step, determine absolute path from relative path, etc.)
Solution: make use of getClass().getResourceAsStream()  and wrap stream to BufferedReader.
