### ISSUE TITLE
TestModelConfiguration broken

### ISSUE THREAD

**Issue by JanKue** [osl2/PhyPiDAQ#33]
Symptom: `TestModelConfiguration` contains several errors.

Cause: Conflict between 29529d13564d7b3f7873cc1cc3ae844036555eae and af7e644cd9e4984feb89ccd4beda18235acea8f9

**Comment by SaturnnrutaS** [comment]
I will take a look at it.

**Comment by JanKue** [comment]
Please confirm whether 6a20fe6f755e8c3389a9a6324f60bd4c4cf5ad86 is a correct solution and if so merge into master.
