### ISSUE TITLE
testWriteIntoYaml() fails half the time

### ISSUE THREAD

**Issue by JanKue** [osl2/PhyPiDAQ#50]
Symptom: The test `TestYamlService.testWriteIntoYaml()` succeeds 50% of the time and fails 50% of the time (alternating).

Cause: In the first test, YamlService successfully writes the file. In the second test, YamlService fails because the file already exists. In the third test, YamlService successfully writes the file again. In the fourth test, YamlService fails again because the file already exists. etc.

**Comment by LinusRuhnke** [comment]
Fixed by Deleting File before every TestRun.
