### ISSUE TITLE
constructBuildingBlock(...) leads to NullPointerException

### ISSUE THREAD

**Issue by JanKue** [osl2/PhyPiDAQ#51]
Symptom: Calling `edu.kit.freejdaq.model.block.Director.constructBuildingBlock(...)` with certain values results in the following `NullPointerException`:

```
java.lang.NullPointerException
	at edu.kit.freejdaq.model.block.SensorKvProcessor.processKvPair(SensorKvProcessor.java:39)
	at edu.kit.freejdaq.model.block.GeneralBlockKvProcessor.processKvPair(GeneralBlockKvProcessor.java:44)
	at edu.kit.freejdaq.model.block.Director.constructBuildingBlock(Director.java:38)
```

**Comment by JanKue** [comment]
Note: problem exists in `GeneralBlockKvProcessor.processKvPair(...)` as well as `SensorKvProcessor.processKvPair(...)`. Switch block attempts to access `blockType` variable which is initialised as null.

**Comment by JanKue** [comment]
Cause: YamlService error

**Comment by LinusRuhnke** [comment]
Is this fixed by now? Additions have been made to check for empty Maps, which are getting returned instead of null.

**Comment by LinusRuhnke** [comment]
Note: Two methods exist to read from a Yaml-File. readFromYaml takes a target path (ex: /properties/testSensor.yaml) and reads out its content. If path doesnt exists it returns a empty Map.
Method readOutAllYaml takes a specific path (ex: src/main/ressources/properties/testSensor.yaml) and read out its content. Currently this method fails if path does not specify a file.

**Comment by JanKue** [comment]
`ModelManager.initializeModel("/prototypes")` is fixed (see `TestModelConfiguration` for example). Some tests in `SensorTest` and `TransformationTest` still seem to fail.

**Comment by LinusRuhnke** [comment]
Building a BuildingBlock fails if yaml-file does not contain the necessary information to. This leads to the NullPointerException. Fixed by checking the BuildingBlock-map for necessary keys

**Comment by JanKue** [comment]
Seems to work correctly now.
