### ISSUE TITLE
quotation marks in saved measurement config can't be opened. 

### ISSUE THREAD

**Issue by stefan-geretschlaeger** [osl2/PhyPiDAQ#54]
Symptom: After saving measurement config, the resulting yaml-file's string value are surrounded by quotes (quotation marks), which doesn't match to the format expected when this file is opened again.

**Comment by JanKue** [comment]
Possible solution: Save content of the editor directly as plain text without parsing it as yaml.

Pros: could solve this specific issue
Cons: no guarantee that the result will be in yaml format at all

**Comment by DavidGawron** [comment]
Cause: snake Yaml has problem dealing with square Brackets used in a file. With our current Settings, it adds single quotes around each square bracket pair.
Removal: added a Method in Fileservice, which parser through the resulting .yaml file and deletes all single quotes.
