### ISSUE TITLE
New Button: Create Graphical Visualisation of Measurement Data.

### ISSUE THREAD

**Issue by LinusRuhnke** [osl2/PhyPiDAQ#71]

**Comment by JanKue** [comment]
Possible technology: https://github.com/jfree/jfreechart

**Comment by JanKue** [comment]
Progress: ea03eea22497595ca00b0633edef703eb0dc5291

**Comment by JanKue** [comment]
9c4b97f7695bae7ea7a2888fb253d5be047e147c
